version: 1
disable_existing_loggers: false

formatters:
  console:
    format: '[%(asctime)s] [%(levelname)s] %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    level: INFO
    formatter: console

loggers:
  uvicorn.access:
    handlers: [console]
    level: INFO
    propagate: false
  root:
    hanlders: [console]
    level: INFO